# Prefix key to CTRL + SPACE
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# True color
set-option -sa terminal-overrides ",xterm*:Tc"

# Mouse movement
set -g mouse on

# ZSH > BASH
set -g default-shell $SHELL

# Top loaded status bar
set -g status-position top 

# Start windows and panes at 1 not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# VIM bindings
# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# vim-like pane resizing
bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R

# Open panes in current directory
bind 'v' split-window -v -c "#{pane_current_path}"
bind 'b' split-window -h -c "#{pane_current_path}"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -g @plugin 'jimeh/tmuxifier'
set -g @plugin 'tmux-plugins/tmux-yank'

# Dracula plugin config
set -g @dracula-plugins "cpu-usage ram-usage battery time git"
set -g @dracula-show-powerline true 
set -g @dracula-show-flags true 
set -g @dracula-show-left-icon session


run '~/.config/tmux/plugins/tpm/tpm'
